name: Release create-codespace-and-checkout

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make script executable
        run:
          cp create-codespace-and-checkout.sh create-codespace-and-checkout
          chmod +x create-codespace-and-checkout

      - name: Create GitHub Release and upload script
        uses: softprops/action-gh-release@v2
        with:
          files: create-codespace-and-checkout
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
